import { useRouter } from "next/router";
import ErrorPage from "next/error";
import Container from "../components/container";
import PostBody from "../components/post-body";
import NavigateBackTo from "../components/navigatebackto";
import PostHeader from "../components/post-header";
import PostTitle from "../components/post-title";
import Head from "next/head";
import type PostType from "../interfaces/post";
import Footer from "../components/footer";
import FetchPostType from "../interfaces/fetchPostType";

type Props = {
  post: PostType;
  navigateBackTo: {
    url: string;
    title: string;
  };
  postType: FetchPostType;
  preview?: boolean;
};

// renders posts for both 'blogs' and 'tils'
export default function Post({ post, navigateBackTo, postType, preview }: Props) {
  const router = useRouter();

  // error has been handled here but as per "fallback: false", if slug is not included in the paths generated by getStaticPaths, error-page will be shown anyways
  if (!router.isFallback && !post?.slug) {
    return <ErrorPage statusCode={404} />;
  }
  return (
    <Container>
      <NavigateBackTo
        url={navigateBackTo.url}
        title={navigateBackTo.title}
        position="top"
      />

      {router.isFallback ? (
        <PostTitle>Loading…</PostTitle>
      ) : (
        <>
          <Head>
            <title>{post.title} | Usman Shaikh</title>
            <meta property="og:image" content={post.ogImage.url} />
          </Head>

          <article className="mb-32">
            <PostHeader
              title={post.title}
              coverImage={post.coverImage}
              date={post.date}
              author={post.author}
              postType={postType}
            />
            <PostBody content={post.content} />
          </article>
        </>
      )}

      <NavigateBackTo
        url={navigateBackTo.url}
        title={navigateBackTo.title}
        position="bottom"
      />
      <Footer />
    </Container>
  );
}
